const products = [
  {
    _id: '1',
    name: 'Apple',
    image: '/images/apple.jpg',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias reiciendis eum distinctio voluptate cum laborum',
    brand: 'ZM',
    category: 'Grocery',
    price: 10.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'Bean',
    image: '/images/bean.jpg',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias reiciendis eum distinctio voluptate cum laborum',
    brand: 'ZM',
    category: 'Grocery',
    price: 10.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '3',
    name: 'Cabbage',
    image: '/images/cabbage.jpg',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias reiciendis eum distinctio voluptate cum laborum',
    brand: 'ZM',
    category: 'Grocery',
    price: 10.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '4',
    name: 'Can',
    image: '/images/can.jpg',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias reiciendis eum distinctio voluptate cum laborum',
    brand: 'ZM',
    category: 'Grocery',
    price: 10.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '5',
    name: 'Cooking Oil',
    image: '/images/cooking-oil.jpg',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias reiciendis eum distinctio voluptate cum laborum',
    brand: 'ZM',
    category: 'Grocery',
    price: 10.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '6',
    name: 'Egg',
    image: '/images/egg.png',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias reiciendis eum distinctio voluptate cum laborum',
    brand: 'ZM',
    category: 'Grocery',
    price: 10.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '7',
    name: 'Fish',
    image: '/images/fish.jpg',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias reiciendis eum distinctio voluptate cum laborum',
    brand: 'ZM',
    category: 'Grocery',
    price: 10.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '8',
    name: 'Grape',
    image: '/images/grape.jpg',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias reiciendis eum distinctio voluptate cum laborum',
    brand: 'ZM',
    category: 'Grocery',
    price: 10.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '9',
    name: 'Meat',
    image: '/images/meat.jpg',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias reiciendis eum distinctio voluptate cum laborum',
    brand: 'ZM',
    category: 'Grocery',
    price: 10.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '10',
    name: 'Orange',
    image: '/images/orange.jpg',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias reiciendis eum distinctio voluptate cum laborum',
    brand: 'ZM',
    category: 'Grocery',
    price: 10.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '11',
    name: 'Pomegranate',
    image: '/images/pomegranate.jpg',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias reiciendis eum distinctio voluptate cum laborum',
    brand: 'ZM',
    category: 'Grocery',
    price: 10.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '12',
    name: 'Tomato',
    image: '/images/tomato.jpg',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias reiciendis eum distinctio voluptate cum laborum',
    brand: 'ZM',
    category: 'Grocery',
    price: 10.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
]

export default products
